#:kivy 2.0.0

<SM>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "media/img/background.jpg"

    Main:
        id: Main
        name: "Main"
    Login:
        id: Login
        name: "Login"
    Registration:
        id: Registration
        name: "Registration"
    Chat:
        id: Chat
        name: "Chat"
    SelectServer:
        id: SelectServer
        name: "SelectServer"

